# shellcheck shell=bash
# ABOUTME: RT-62.1 - example site build contains an audiobook page for demo content.

# What user action does this test simulate?
#   A visitor opens the example site's audiobook demo URL.
# What would the user observe?
#   The browser receives an audiobook page generated by the theme.

source "$(dirname "${BASH_SOURCE[0]}")/_helpers.sh"

run_test() {
    local page
    page="$(audiobook_demo_page)" || return 1
    [[ -f "$page" ]]
}
